apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web3-deployment
  labels:
    app : my-k8s3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: test3
  template:
    metadata:
      labels:
        project: test3   
    spec:
      containers:
        - name : test3-web
          image: httpd:latest
          ports:
            - containerPort: 80
