apiVersion: v1
kind: Service
metadata:
  name: my-single-pod3-service
  labels:
    env  : prod
    owner: Alex
spec: 
  selector:
    project: test3  
  ports:
    - name      : app3-listener
      protocol  : TCP
      port      : 80  
      targetPort: 80  
  type: LoadBalancer
