apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: test1
  template:
    metadata:
      labels:
        project: test1  
    spec:
      containers:
        - name : test1-web
          image: httpd:latest
          ports:
            - containerPort: 80
