apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app : my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: test2
  template:
    metadata:
      labels:
        project: test2 
    spec:
      containers:
        - name : test2
          image: httpd:latest
          ports:
            - containerPort: 80
