apiVersion: v1
kind: Service
metadata:
  name: my-single-pod2-service
  labels:
    env  : prod
    owner: Alex
spec:
  selector:
    project: test2  
  ports:
    - name      : app2-listener
      protocol  : TCP
      port      : 80 
      targetPort: 80  
  type: LoadBalancer
